import type { Metadata } from "next";
import { PrintButton } from "@/components/print-button";
import { QR_TARGET_URL, SITE_HOST } from "@/lib/config";

export const metadata: Metadata = {
  title: "Scan Me",
  robots: { index: false, follow: false },
};

/**
 * Print-ready "Scan Me" flyer. Open this route and print straight from the
 * browser. The QR image is public/qr/scan-me.svg, generated by `npm run qr`,
 * and encodes QR_TARGET_URL. Nothing else lives on this page on purpose —
 * the branding is on the landing page the QR opens.
 */
export default function ScanPage() {
  return (
    <main className="scan">
      <h1 className="scan__title">SCAN ME</h1>
      {/* Plain <img>: SVG asset from /public, no optimizer needed. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        className="scan__qr"
        src="/qr/scan-me.svg"
        alt={`QR code linking to ${QR_TARGET_URL}`}
        width={480}
        height={480}
      />
      <p className="scan__url">{SITE_HOST}</p>
      <PrintButton />
    </main>
  );
}
